### ISSUE TITLE
How to set the RMap put timeout

### ISSUE THREAD

**Issue by wmz7year** [mrniko/redisson#157]
Hello  I'm testing the redisson with Master/Slave module .
When redis memory is exhaustion the RMap.put will be wait.
There is no any Exception or someting.
Is anyway to fix this?

**Comment by mrniko** [comment]
does redis have error in this situation?

**Comment by Gladmir** [comment]
When available/mappable memory runs out, Redis simply blocks the write requests for every each client/connection, since its event/request loop is single threaded.

Depending on the default configured timeouts, you should get read or write io timeout exception from the underlying socket implementation (Netty in this case).

**Comment by mrniko** [comment]
@wmz7year you may tune LRU eviction mechanism which [Redis supports](http://redis.io/topics/lru-cache).

**Comment by mrniko** [comment]
@wmz7year it's done in #195 !
