### ISSUE TITLE
RLock.tryLock() thows Exception

### ISSUE THREAD

**Issue by turbospaces** [mrniko/redisson#229]
**org.redisson.client.RedisException: ERR Error running script (call to f_2d027cdc209d32fe7dade9ba284110f88d497180): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value . channel: [id: 0x24baaaa8, /192.168.99.1:64875 => /192.168.99.100:6379]**

ENV: redis 3.0.3/2.8.3
REDISSON: 2.1.1/1.3.1

**Comment by mrniko** [comment]
> WRONGTYPE Operation against a key holding the wrong kind of value

Could you provide a test case? because redisson own lock tests are always pass

**Comment by turbospaces** [comment]
really i can't understand how it's possible, but here is an example

```java
     Redisson redisson = Redisson.create();
      try {
            RLock lock = redisson.getLock( "rest-example" );
            boolean result = lock.tryLock();
            if ( result ) {
                try {

                }
                finally {
                    lock.unlock();
                }
            }
        }
        finally {
            redisson.shutdown();
        }
```

I tried to change 'rest-example' to other words, but then it works. I don't know what is so special in this word, any ideas?

**Comment by mrniko** [comment]
Can't reproduce with 2.1.4

**Comment by Kindrat** [comment]
Same here

ENV: redis:3 docker image
REDISSON: 2.1.5

**Redis server response timeout for command: (EVAL) with params: [local v = redis.call('get', KEYS[1]); if (v == false) then   redis.call('set', KEYS[1], cjson.encode({['o'] = ARGV[1], ['c'] = 1}), 'px', ARGV[2]);   return nil; else   local o = cjson.decode(v);   if (o['o'] == ARGV[1]) then     o['c'] = o['c'] + 1; redis.call('set', KEYS[1], cjson.encode(o), 'px', ARGV[2]);     return nil;   end;  return redis.call('pttl', KEYS[1]); end, 1, TestTemplate1, 1a8ae891-30f0-445b-a236-facb02d607fe-19, 30000] channel: [id: 0xe60a6776, /127.0.0.1:51336 :> /127.0.0.1:6379]**

```java
List<RLock> lockedKeys = new ArrayList<>();

try {
  Iterator<String> keyIterator = redisson.<String>getSet(KEY_STORAGE).iterator();
  while (keyIterator.hasNext()) {
    String key = keyIterator.next();
    RLock lock = redisson.getLock(key);

    if (lock.tryLock()) {
      lockedKeys.add(lock);
      doWork();
    }
  }
} finally {
  lockedKeys.forEach(RLock::forceUnlock);
}
```

KEY_STORAGE is just a set with copies of created keys saved as values to use instead of expensive keys() command and additional filtering.

Any thoughts? Or am I just using locks in a wrong way?

**Comment by mrniko** [comment]
> Any thoughts? Or am I just using locks in a wrong way?

This error occurs when redis command has been sent, but redis response timeout occured. Which timeout (via `setTimeout` method) you have set?

**Comment by Kindrat** [comment]
``` java
        Config config = new Config().setThreads(1).setCodec(new KryoCodec());
        config.useSingleServer()
                .setAddress(properties.getHost())
                .setConnectionMinimumIdleSize(properties.getMinIdle())
                .setConnectionPoolSize(properties.getMaxActive())
                .setConnectTimeout(properties.getConnectionTimeout())
                .setClientName("AutoConfigured")
                .setDatabase(properties.getDatabase())
                .setPassword(properties.getPassword());
```

**Comment by mrniko** [comment]
by default timeout is equals to 1 sec. I think such time amount should be enough for redis response.

**Comment by Kindrat** [comment]
With increased timeout everything seems fine now. Thanks. Should increase docker limits.

**Comment by ElvisWang** [comment]
Did you have set a key have the same name  of "rest-example" in another way? 
I got the same issue, my solution is del the duplicate key and retry, then bingo ,fixed; 
Hope my solution can help you ;
